export interface SEOResult {
  title: string;
  description: string;
  keywords: string[];
}

export async function seoOptimizer(
  topic: string,
  summary: string,
  keywords: string[]
): Promise<SEOResult> {

  const title =
    topic.length > 60
      ? topic.slice(0, 60)
      : topic;

  const description = `${summary}

Keywords:
${keywords.join(", ")}

Generated by ViralClip AI`;

  return {
    title,
    description,
    keywords,
  };
}