"use client";

import {
  Sparkles,
  TrendingUp,
  Brain,
  Hash,
  FileText,
  Lightbulb,
  CheckCircle2,
} from "lucide-react";

import Card from "@/components/ui/Card";

interface Props {
  analysis?: any;
}

export default function AIAnalysis({
  analysis,
}: Props) {

  if (!analysis) {
    return (
      <Card>
        <div className="flex h-[420px] flex-col items-center justify-center">

          <Brain className="mb-4 h-16 w-16 text-slate-600" />

          <h2 className="text-xl font-bold text-white">
            AI Analysis
          </h2>

          <p className="mt-2 text-slate-400">
            Upload a video to generate AI insights.
          </p>

        </div>
      </Card>
    );
  }

 return (
  <Card>
    <div className="mb-6 flex items-center justify-between">
      <div>
        <h2 className="text-xl font-bold text-white">
          AI Intelligence
        </h2>

        <p className="text-sm text-slate-400">
          Generated by ViralClip AI Engine
        </p>
      </div>

      <div className="rounded-full bg-emerald-500/10 px-4 py-2">
        <span className="font-semibold text-emerald-400">
          COMPLETE
        </span>
      </div>
    </div>

    {/* Score */}

    <div className="mb-6 rounded-2xl border border-emerald-500/20 bg-gradient-to-r from-emerald-500/10 to-blue-500/10 p-6">

      <div className="flex items-center justify-between">

        <div>

          <p className="text-sm text-slate-400">
            Viral Score
          </p>

          <h2 className="mt-2 text-5xl font-extrabold text-emerald-400">
            {analysis.overall_score ?? 0}%
          </h2>

        </div>

        <TrendingUp className="h-14 w-14 text-emerald-400" />

      </div>

      <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-800">

        <div
          className="h-full rounded-full bg-gradient-to-r from-emerald-400 to-cyan-400"
          style={{
            width: `${analysis.overall_score ?? 0}%`,
          }}
        />

      </div>

    </div>

    {/* Metrics */}

    <div className="grid gap-4 md:grid-cols-2">

      <Metric
        title="AI Confidence"
        value="98%"
        icon={<CheckCircle2 className="h-5 w-5 text-blue-400" />}
      />

      <Metric
        title="Content Quality"
        value={`${analysis.overall_score ?? 0}%`}
        icon={<Brain className="h-5 w-5 text-violet-400" />}
      />

    </div>

    {/* Summary */}

    <Section
      icon={<FileText className="h-5 w-5 text-cyan-400" />}
      title="AI Summary"
    >
      {analysis.intelligence ??
        "AI summary will appear after processing."}
    </Section>

    {/* Hook */}

    <Section
      icon={<Sparkles className="h-5 w-5 text-yellow-400" />}
      title="Best Hook"
    >
      {analysis.hook ??
        "No hook generated yet."}
    </Section>

    {/* Keywords */}

    <Section
      icon={<Hash className="h-5 w-5 text-purple-400" />}
      title="Keywords"
    >
      {analysis.keywords ??
        "No keywords generated."}
    </Section>

    {/* Recommendation */}

    <Section
      icon={<Lightbulb className="h-5 w-5 text-orange-400" />}
      title="AI Recommendation"
    >
      {analysis.recommendation ??
        "Generate multiple clips and publish to TikTok, Instagram Reels, YouTube Shorts and Facebook Reels for maximum reach."}
    </Section>

  </Card>
);
function Metric({
  title,
  value,
  icon,
}: {
  title: string;
  value: string;
  icon: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900 p-4">

      <div className="flex items-center gap-2">

        {icon}

        <span className="text-sm text-slate-400">
          {title}
        </span>

      </div>

      <h3 className="mt-3 text-3xl font-bold text-white">
        {value}
      </h3>

    </div>
  );
}

function Section({
  title,
  icon,
  children,
}: {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-4 rounded-xl border border-slate-800 bg-slate-900 p-5">

      <div className="mb-3 flex items-center gap-2">

        {icon}

        <h3 className="font-semibold text-white">
          {title}
        </h3>

      </div>

      <p className="leading-7 text-slate-300">
        {children}
      </p>

    </div>
   )}


}