"use client";

import {
  Copy,
  Download,
  RefreshCw,
  Sparkles,
} from "lucide-react";

interface Props {
  result: string;
  title: string;
}

export default function AIResults({
  result,
  title,
}: Props) {
  async function copyResult() {
    await navigator.clipboard.writeText(result);
    alert("Copied successfully.");
  }

  function downloadResult() {
    const blob = new Blob([result], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download = `${title}.txt`;

    a.click();

    URL.revokeObjectURL(url);
  }

  if (!result) {
    return (
      <div className="rounded-3xl border border-[#4a3426] bg-[#15100c] p-12 text-center">
        <Sparkles className="mx-auto mb-5 h-14 w-14 text-orange-400" />

        <h2 className="text-3xl font-bold text-white">
          AI Results
        </h2>

        <p className="mt-3 text-slate-400">
          Run any AI tool and the generated content will appear here.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-3xl border border-[#4a3426] bg-[#15100c]">

      <div className="flex items-center justify-between border-b border-[#4a3426] bg-[#201712] px-6 py-5">

        <div>

          <p className="text-xs uppercase tracking-[0.25em] text-orange-400">
            AI OUTPUT
          </p>

          <h2 className="mt-1 text-2xl font-bold text-white">
            {title}
          </h2>

          <p className="mt-1 text-sm text-slate-400">
            Generated by ViralClip AI
          </p>

        </div>

        <div className="flex gap-3">

          <button
            onClick={copyResult}
            className="rounded-xl bg-[#2b2019] p-3 text-slate-300 transition hover:bg-[#3a2a21]"
          >
            <Copy size={18} />
          </button>

          <button
            onClick={downloadResult}
            className="rounded-xl bg-[#2b2019] p-3 text-slate-300 transition hover:bg-[#3a2a21]"
          >
            <Download size={18} />
          </button>

          <button
            className="rounded-xl bg-gradient-to-r from-red-600 to-orange-500 p-3 text-white transition hover:from-red-500 hover:to-orange-400"
          >
            <RefreshCw size={18} />
          </button>

        </div>

      </div>

      <div className="p-6">

        <textarea
          readOnly
          value={result}
          className="min-h-[420px] w-full resize-none rounded-2xl border border-[#4a3426] bg-[#100c09] p-6 text-base leading-8 text-slate-200 outline-none"
        />

      </div>

    </div>
  );
}